---
### This is A suse instalation
- hosts: "cems"
  vars:
    information_apps:
     - nmon
#     - bmon
     - htop
     - iftop
    network_apps:
     - net-tools
    mysql80repo:
     - https://dev.mysql.com/get/mysql80-community-release-sles12-1.noarch.rpm 
#     - epel-release
    mysql_install_server:
     - mysql-community-client 
     - mysql-community-common 
     - mysql-community-libs 
     - mysql-community-server
    bash:
     - bash-com*
    file_manipulation:
     - rsync
     - mc
     - unzip
    rpm_package:
     - https://dev.mysql.com/get/mysql80-community-release-sles12-1.noarch.rpm
    mysql_enable_repo:
     -mysql57-community
     -mysql57-community-source
    mysql_disable_repo:
     mysql56-community
     mysql57-community
     mysql80-community
#
  tasks:
#  - name: epel-release
#    package:                                                                                                         
#     name: "{{repo}}"                                                                                                
#     state: present                                                                                                  
  - name: install information_apps                                                                                   
    package:                                                                                                         
     name: "{{information_apps}}"
     state: present
     disable_gpg_check: yes
  - name: install network_apps
    package:
     name: "{{network_apps}}"
     state: present
     disable_gpg_check: yes
  - name: Install bash-compleation
    package:
     name: "{{bash}}"
     state: present
     disable_gpg_check: yes
  - name: File manipulation
    package:
     name: "{{file_manipulation}}"
     state: present
     disable_gpg_check: yes
  - name: install rpm Mysql 8 repo suse
    package:
     name: "{{rpm_package}}"
     state: present
     disable_gpg_check: yes








#  - name: Mysql 8 repo
#    zypper:
#     name: "{{mysql80repo}}"
#     state: present 
#     disable_gpg_check: yes
#  - name: disable all suse mysql repos for suse
#    command: zypper modifyrepo -d "{{mysql_disable_repo}}"
#  - name: enable mysql repos for suse
#    command: zypper modifyrepo -e "{{mysql_enable_repo}}"
  - name: disable all suse mysql repos for suse
    command: zypper modifyrepo -d mysql80-community
  - name: disable suse mysql mysql56-community for suse
    command: zypper modifyrepo -d mysql56-community
  - name: disable suse mysql mysql57-community for suse
    command: zypper modifyrepo -d mysql57-community
  - name: disable suse mysql mysql80-community for suse
    command: zypper modifyrepo -d mysql80-community
  - name: enable suse mysql mysql57-community for suse
    command: zypper modifyrepo -e mysql57-community

  - name: install Mysql server 
    package:
     name: "{{mysql_install_server}}"
     state: present
     disable_gpg_check: yes
 









#   name: mysql80
#    zypper_repository:
#     name: mysql-community
#     repo: 'https://dev.mysql.com/get/mysql80-community-release-sles12-1.noarch.rpm'
#     state: present
#     auto_import_keys: yes
#  - name: update
#    package:
#     name: "*"
#     state: latest
#     disable_gpg_check: yes
  - name: copy my.cnf                      
    copy:
     src: /root/Ansible/mycnf.conf
     dest: /etc/my.cnf
     owner: root
     group: root
     mode: u=rw,g=r,o=r
  - name: enabeling 
    
## skip-grant-tables

  
#  - name: Start MySQL
#    service:
#     name: mysql
#     state: started
#     enabled: yes   
    lineinfile:
     path: /etc/my.cnf
     regexp: '^## skip-grant-tables'
     line: 'skip-grant-tables'

#  - name: se linux disable
#    lineinfile:
#     path: /etc/selinux/config
#     regexp: '^SELINUX='
#     line: 'SELINUX=disabled' 
#  - name: install rpm package
#    command: rpm -i "{{rpm_package}}"



#     register: state
#     diebug: var=latest.stdout_lines



#  - name: Classify hosts depending on their OS distribution
#    group_by:
#     key: os_{{ ansible_facts['distribution'] }}
#  - hosts: os_CentOS
#     gather_facts: False
#     tasks:  
#     - name: update the system
#       yum:
#       name: "*"
#       state: latest 
#---------------------------------------------
##doesnot work becaouse i think its a rpm
##  - zypper_repository:
##     name: Mysql 8 repo
##     repo: https://dev.mysql.com/get/mysql80-community-release-sles12-1.noarch.rpm
##     state: present
##     auto_import_keys: yes
##     disable_gpg_check: yes
##     enabled: no 
#
