---
- hosts: slave173
  vars:
    information_apps:
     - nmon
     - bmon
     - htop
     - iftop
    network_apps:
     - net-tools
    repo:
     - epel-release
    bash:
     - bash-com*
    file_manipulation:
     - rsync
     - mc
     - unzip
         
  tasks:
  - name: epel-release
    package:                                                                                                         
     name: "{{repo}}"                                                                                                
     state: present                                                                                                  
  - name: install information_apps                                                                                   
    package:                                                                                                         
     name: "{{information_apps}}"                                                                                    
     state: present
  - name: install network_apps
    package:
     name: "{{network_apps}}"
     state: present
  - name: Install bash-compleation
    package:
     name: "{{bash}}"
     state: present
  - name: File manipulation
    package:
     name: "{{file_manipulation}}"
     state: present
  - name: se linux disable
    lineinfile:
     path: /etc/selinux/config
     regexp: '^SELINUX='
     line: 'SELINUX=disabled' 
  - name: update
    package:
     name: "*"
     state: latest





#     register: state
#     debug: var=latest.stdout_lines



#  - name: Classify hosts depending on their OS distribution
#    group_by:
#     key: os_{{ ansible_facts['distribution'] }}
#  - hosts: os_CentOS
#     gather_facts: False
#     tasks:  
#     - name: update the system
#       yum:
#       name: "*"
#       state: latest  
